[general]
import = ["~/.config/alacritty/themes/gruvbox-dark.toml"]

[terminal]
shell = "zsh"

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
WINIT_X11_SCALE_FACTOR = "1"
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"

[scrolling]
history = 10000
multiplier = 3
