[terminal]
shell = "zsh"

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
WINIT_X11_SCALE_FACTOR = "1"
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 1.0

[window.class]
general = "Alacritty"
instance = "Alacritty"


# [colors.primary]
# background = "#282828"
# foreground = "#d4be98"
#
# [colors.normal]
# black = "0x665c54"
# red = "0xea6962"
# green = "0xa9b665"
# yellow = "0xe78a4e"
# blue = "0x7daea3"
# magenta = "0xd3869b"
# cyan = "0x89b482"
# white = "0xd4be98"
#
# [colors.bright]
# black = "0x928374"
# red = "0xea6962"
# green = "0xa9b665"
# yellow = "0xd8a657"
# blue = "0x7daea3"
# magenta = "0xd3869b"
# cyan = "0x89b482"
# white = "0xd4be98"
#
# Colors (Gruvbox light)

# Default colors
[colors.primary]
# hard contrast background = = '#f9f5d7'
background = '#f9f5d7'
# soft contrast background = = '#f2e5bc'
foreground = '#3c3836'

# Normal colors
[colors.normal]
black   = '#f9f5d7'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#7c6f64'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#9d0006'
green   = '#79740e'
yellow  = '#b57614'
blue    = '#076678'
magenta = '#8f3f71'
cyan    = '#427b58'
white   = '#3c3836'
