[terminal]
shell = "zsh"

[colors.primary]
background = "#282828"
foreground = "#d4be98"

[colors.normal]
black = "0x665c54"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xe78a4e"
blue = "0x7daea3"
magenta = "0xd3869b"
cyan = "0x89b482"
white = "0xd4be98"

[colors.bright]
black = "0x928374"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xd8a657"
blue = "0x7daea3"
magenta = "0xd3869b"
cyan = "0x89b482"
white = "0xd4be98"

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 1.0

[window.class]
general = "Alacritty"
instance = "Alacritty"
